# Generated by Django 4.0.4 on 2022-06-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacao',
            name='nome_do_anime',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='nome',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='top',
            name='nome',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
