# Generated by Django 4.0.4 on 2022-06-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashb', '0002_estacao_nome_do_anime_alter_estacao_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inverno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_anime', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_anime', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Primavera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_anime', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Verao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_anime', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Estacao',
        ),
    ]
