# Generated by Django 4.0.4 on 2022-06-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashb', '0003_inverno_outono_primavera_verao_delete_estacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaisVisto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_anime', models.CharField(max_length=50, null=True)),
                ('qtd_views', models.IntegerField()),
            ],
        ),
    ]
